/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as NewsIndexRouteImport } from './routes/news.index'
import { Route as ServicesServiceIdRouteImport } from './routes/services.$serviceId'
import { Route as NewsIdRouteImport } from './routes/news.$id'
import { Route as DashboardProviderRouteImport } from './routes/dashboard.provider'
import { Route as DashboardHomeownerRouteImport } from './routes/dashboard.homeowner'
import { Route as DashboardAdminRouteImport } from './routes/dashboard.admin'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as UsernameBookRouteImport } from './routes/$username.book'
import { Route as ServicesServiceIdIndexRouteImport } from './routes/services.$serviceId.index'
import { Route as ServicesServiceIdSubServiceIdRouteImport } from './routes/services.$serviceId.$subServiceId'
import { Route as AuthenticatedUsernameWalletRouteImport } from './routes/_authenticated.$username.wallet'
import { Route as AuthenticatedUsernameSecurityRouteImport } from './routes/_authenticated.$username.security'
import { Route as AuthenticatedUsernameProfileRouteImport } from './routes/_authenticated.$username.profile'
import { Route as AuthenticatedUsernamePastBookingsRouteImport } from './routes/_authenticated.$username.past-bookings'
import { Route as AuthenticatedUsernameNewJobsRouteImport } from './routes/_authenticated.$username.new-jobs'
import { Route as AuthenticatedUsernameJobsBookingsRouteImport } from './routes/_authenticated.$username.jobs-bookings'
import { Route as AuthenticatedUsernameJobsRouteImport } from './routes/_authenticated.$username.jobs'
import { Route as AuthenticatedUsernameDashboardRouteImport } from './routes/_authenticated.$username.dashboard'
import { Route as AuthenticatedUsernameActiveBookingsRouteImport } from './routes/_authenticated.$username.active-bookings'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIndexRoute = NewsIndexRouteImport.update({
  id: '/news/',
  path: '/news/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesServiceIdRoute = ServicesServiceIdRouteImport.update({
  id: '/services/$serviceId',
  path: '/services/$serviceId',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsIdRoute = NewsIdRouteImport.update({
  id: '/news/$id',
  path: '/news/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProviderRoute = DashboardProviderRouteImport.update({
  id: '/dashboard/provider',
  path: '/dashboard/provider',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardHomeownerRoute = DashboardHomeownerRouteImport.update({
  id: '/dashboard/homeowner',
  path: '/dashboard/homeowner',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/dashboard/admin',
  path: '/dashboard/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const UsernameBookRoute = UsernameBookRouteImport.update({
  id: '/$username/book',
  path: '/$username/book',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesServiceIdIndexRoute = ServicesServiceIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesServiceIdRoute,
} as any)
const ServicesServiceIdSubServiceIdRoute =
  ServicesServiceIdSubServiceIdRouteImport.update({
    id: '/$subServiceId',
    path: '/$subServiceId',
    getParentRoute: () => ServicesServiceIdRoute,
  } as any)
const AuthenticatedUsernameWalletRoute =
  AuthenticatedUsernameWalletRouteImport.update({
    id: '/$username/wallet',
    path: '/$username/wallet',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsernameSecurityRoute =
  AuthenticatedUsernameSecurityRouteImport.update({
    id: '/$username/security',
    path: '/$username/security',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsernameProfileRoute =
  AuthenticatedUsernameProfileRouteImport.update({
    id: '/$username/profile',
    path: '/$username/profile',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsernamePastBookingsRoute =
  AuthenticatedUsernamePastBookingsRouteImport.update({
    id: '/$username/past-bookings',
    path: '/$username/past-bookings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsernameNewJobsRoute =
  AuthenticatedUsernameNewJobsRouteImport.update({
    id: '/$username/new-jobs',
    path: '/$username/new-jobs',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsernameJobsBookingsRoute =
  AuthenticatedUsernameJobsBookingsRouteImport.update({
    id: '/$username/jobs-bookings',
    path: '/$username/jobs-bookings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsernameJobsRoute =
  AuthenticatedUsernameJobsRouteImport.update({
    id: '/$username/jobs',
    path: '/$username/jobs',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsernameDashboardRoute =
  AuthenticatedUsernameDashboardRouteImport.update({
    id: '/$username/dashboard',
    path: '/$username/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedUsernameActiveBookingsRoute =
  AuthenticatedUsernameActiveBookingsRouteImport.update({
    id: '/$username/active-bookings',
    path: '/$username/active-bookings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/$username/book': typeof UsernameBookRoute
  '/admin/login': typeof AdminLoginRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/homeowner': typeof DashboardHomeownerRoute
  '/dashboard/provider': typeof DashboardProviderRoute
  '/news/$id': typeof NewsIdRoute
  '/services/$serviceId': typeof ServicesServiceIdRouteWithChildren
  '/news/': typeof NewsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/$username/active-bookings': typeof AuthenticatedUsernameActiveBookingsRoute
  '/$username/dashboard': typeof AuthenticatedUsernameDashboardRoute
  '/$username/jobs': typeof AuthenticatedUsernameJobsRoute
  '/$username/jobs-bookings': typeof AuthenticatedUsernameJobsBookingsRoute
  '/$username/new-jobs': typeof AuthenticatedUsernameNewJobsRoute
  '/$username/past-bookings': typeof AuthenticatedUsernamePastBookingsRoute
  '/$username/profile': typeof AuthenticatedUsernameProfileRoute
  '/$username/security': typeof AuthenticatedUsernameSecurityRoute
  '/$username/wallet': typeof AuthenticatedUsernameWalletRoute
  '/services/$serviceId/$subServiceId': typeof ServicesServiceIdSubServiceIdRoute
  '/services/$serviceId/': typeof ServicesServiceIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/$username/book': typeof UsernameBookRoute
  '/admin/login': typeof AdminLoginRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/homeowner': typeof DashboardHomeownerRoute
  '/dashboard/provider': typeof DashboardProviderRoute
  '/news/$id': typeof NewsIdRoute
  '/news': typeof NewsIndexRoute
  '/services': typeof ServicesIndexRoute
  '/$username/active-bookings': typeof AuthenticatedUsernameActiveBookingsRoute
  '/$username/dashboard': typeof AuthenticatedUsernameDashboardRoute
  '/$username/jobs': typeof AuthenticatedUsernameJobsRoute
  '/$username/jobs-bookings': typeof AuthenticatedUsernameJobsBookingsRoute
  '/$username/new-jobs': typeof AuthenticatedUsernameNewJobsRoute
  '/$username/past-bookings': typeof AuthenticatedUsernamePastBookingsRoute
  '/$username/profile': typeof AuthenticatedUsernameProfileRoute
  '/$username/security': typeof AuthenticatedUsernameSecurityRoute
  '/$username/wallet': typeof AuthenticatedUsernameWalletRoute
  '/services/$serviceId/$subServiceId': typeof ServicesServiceIdSubServiceIdRoute
  '/services/$serviceId': typeof ServicesServiceIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/$username/book': typeof UsernameBookRoute
  '/admin/login': typeof AdminLoginRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/homeowner': typeof DashboardHomeownerRoute
  '/dashboard/provider': typeof DashboardProviderRoute
  '/news/$id': typeof NewsIdRoute
  '/services/$serviceId': typeof ServicesServiceIdRouteWithChildren
  '/news/': typeof NewsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/_authenticated/$username/active-bookings': typeof AuthenticatedUsernameActiveBookingsRoute
  '/_authenticated/$username/dashboard': typeof AuthenticatedUsernameDashboardRoute
  '/_authenticated/$username/jobs': typeof AuthenticatedUsernameJobsRoute
  '/_authenticated/$username/jobs-bookings': typeof AuthenticatedUsernameJobsBookingsRoute
  '/_authenticated/$username/new-jobs': typeof AuthenticatedUsernameNewJobsRoute
  '/_authenticated/$username/past-bookings': typeof AuthenticatedUsernamePastBookingsRoute
  '/_authenticated/$username/profile': typeof AuthenticatedUsernameProfileRoute
  '/_authenticated/$username/security': typeof AuthenticatedUsernameSecurityRoute
  '/_authenticated/$username/wallet': typeof AuthenticatedUsernameWalletRoute
  '/services/$serviceId/$subServiceId': typeof ServicesServiceIdSubServiceIdRoute
  '/services/$serviceId/': typeof ServicesServiceIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/privacy'
    | '/profile'
    | '/signup'
    | '/terms'
    | '/$username/book'
    | '/admin/login'
    | '/dashboard/admin'
    | '/dashboard/homeowner'
    | '/dashboard/provider'
    | '/news/$id'
    | '/services/$serviceId'
    | '/news/'
    | '/services/'
    | '/$username/active-bookings'
    | '/$username/dashboard'
    | '/$username/jobs'
    | '/$username/jobs-bookings'
    | '/$username/new-jobs'
    | '/$username/past-bookings'
    | '/$username/profile'
    | '/$username/security'
    | '/$username/wallet'
    | '/services/$serviceId/$subServiceId'
    | '/services/$serviceId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/privacy'
    | '/profile'
    | '/signup'
    | '/terms'
    | '/$username/book'
    | '/admin/login'
    | '/dashboard/admin'
    | '/dashboard/homeowner'
    | '/dashboard/provider'
    | '/news/$id'
    | '/news'
    | '/services'
    | '/$username/active-bookings'
    | '/$username/dashboard'
    | '/$username/jobs'
    | '/$username/jobs-bookings'
    | '/$username/new-jobs'
    | '/$username/past-bookings'
    | '/$username/profile'
    | '/$username/security'
    | '/$username/wallet'
    | '/services/$serviceId/$subServiceId'
    | '/services/$serviceId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/login'
    | '/privacy'
    | '/profile'
    | '/signup'
    | '/terms'
    | '/$username/book'
    | '/admin/login'
    | '/dashboard/admin'
    | '/dashboard/homeowner'
    | '/dashboard/provider'
    | '/news/$id'
    | '/services/$serviceId'
    | '/news/'
    | '/services/'
    | '/_authenticated/$username/active-bookings'
    | '/_authenticated/$username/dashboard'
    | '/_authenticated/$username/jobs'
    | '/_authenticated/$username/jobs-bookings'
    | '/_authenticated/$username/new-jobs'
    | '/_authenticated/$username/past-bookings'
    | '/_authenticated/$username/profile'
    | '/_authenticated/$username/security'
    | '/_authenticated/$username/wallet'
    | '/services/$serviceId/$subServiceId'
    | '/services/$serviceId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  UsernameBookRoute: typeof UsernameBookRoute
  AdminLoginRoute: typeof AdminLoginRoute
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardHomeownerRoute: typeof DashboardHomeownerRoute
  DashboardProviderRoute: typeof DashboardProviderRoute
  NewsIdRoute: typeof NewsIdRoute
  ServicesServiceIdRoute: typeof ServicesServiceIdRouteWithChildren
  NewsIndexRoute: typeof NewsIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/': {
      id: '/news/'
      path: '/news'
      fullPath: '/news/'
      preLoaderRoute: typeof NewsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$serviceId': {
      id: '/services/$serviceId'
      path: '/services/$serviceId'
      fullPath: '/services/$serviceId'
      preLoaderRoute: typeof ServicesServiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news/$id': {
      id: '/news/$id'
      path: '/news/$id'
      fullPath: '/news/$id'
      preLoaderRoute: typeof NewsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/provider': {
      id: '/dashboard/provider'
      path: '/dashboard/provider'
      fullPath: '/dashboard/provider'
      preLoaderRoute: typeof DashboardProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/homeowner': {
      id: '/dashboard/homeowner'
      path: '/dashboard/homeowner'
      fullPath: '/dashboard/homeowner'
      preLoaderRoute: typeof DashboardHomeownerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/dashboard/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username/book': {
      id: '/$username/book'
      path: '/$username/book'
      fullPath: '/$username/book'
      preLoaderRoute: typeof UsernameBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$serviceId/': {
      id: '/services/$serviceId/'
      path: '/'
      fullPath: '/services/$serviceId/'
      preLoaderRoute: typeof ServicesServiceIdIndexRouteImport
      parentRoute: typeof ServicesServiceIdRoute
    }
    '/services/$serviceId/$subServiceId': {
      id: '/services/$serviceId/$subServiceId'
      path: '/$subServiceId'
      fullPath: '/services/$serviceId/$subServiceId'
      preLoaderRoute: typeof ServicesServiceIdSubServiceIdRouteImport
      parentRoute: typeof ServicesServiceIdRoute
    }
    '/_authenticated/$username/wallet': {
      id: '/_authenticated/$username/wallet'
      path: '/$username/wallet'
      fullPath: '/$username/wallet'
      preLoaderRoute: typeof AuthenticatedUsernameWalletRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/$username/security': {
      id: '/_authenticated/$username/security'
      path: '/$username/security'
      fullPath: '/$username/security'
      preLoaderRoute: typeof AuthenticatedUsernameSecurityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/$username/profile': {
      id: '/_authenticated/$username/profile'
      path: '/$username/profile'
      fullPath: '/$username/profile'
      preLoaderRoute: typeof AuthenticatedUsernameProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/$username/past-bookings': {
      id: '/_authenticated/$username/past-bookings'
      path: '/$username/past-bookings'
      fullPath: '/$username/past-bookings'
      preLoaderRoute: typeof AuthenticatedUsernamePastBookingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/$username/new-jobs': {
      id: '/_authenticated/$username/new-jobs'
      path: '/$username/new-jobs'
      fullPath: '/$username/new-jobs'
      preLoaderRoute: typeof AuthenticatedUsernameNewJobsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/$username/jobs-bookings': {
      id: '/_authenticated/$username/jobs-bookings'
      path: '/$username/jobs-bookings'
      fullPath: '/$username/jobs-bookings'
      preLoaderRoute: typeof AuthenticatedUsernameJobsBookingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/$username/jobs': {
      id: '/_authenticated/$username/jobs'
      path: '/$username/jobs'
      fullPath: '/$username/jobs'
      preLoaderRoute: typeof AuthenticatedUsernameJobsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/$username/dashboard': {
      id: '/_authenticated/$username/dashboard'
      path: '/$username/dashboard'
      fullPath: '/$username/dashboard'
      preLoaderRoute: typeof AuthenticatedUsernameDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/$username/active-bookings': {
      id: '/_authenticated/$username/active-bookings'
      path: '/$username/active-bookings'
      fullPath: '/$username/active-bookings'
      preLoaderRoute: typeof AuthenticatedUsernameActiveBookingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedUsernameActiveBookingsRoute: typeof AuthenticatedUsernameActiveBookingsRoute
  AuthenticatedUsernameDashboardRoute: typeof AuthenticatedUsernameDashboardRoute
  AuthenticatedUsernameJobsRoute: typeof AuthenticatedUsernameJobsRoute
  AuthenticatedUsernameJobsBookingsRoute: typeof AuthenticatedUsernameJobsBookingsRoute
  AuthenticatedUsernameNewJobsRoute: typeof AuthenticatedUsernameNewJobsRoute
  AuthenticatedUsernamePastBookingsRoute: typeof AuthenticatedUsernamePastBookingsRoute
  AuthenticatedUsernameProfileRoute: typeof AuthenticatedUsernameProfileRoute
  AuthenticatedUsernameSecurityRoute: typeof AuthenticatedUsernameSecurityRoute
  AuthenticatedUsernameWalletRoute: typeof AuthenticatedUsernameWalletRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedUsernameActiveBookingsRoute:
    AuthenticatedUsernameActiveBookingsRoute,
  AuthenticatedUsernameDashboardRoute: AuthenticatedUsernameDashboardRoute,
  AuthenticatedUsernameJobsRoute: AuthenticatedUsernameJobsRoute,
  AuthenticatedUsernameJobsBookingsRoute:
    AuthenticatedUsernameJobsBookingsRoute,
  AuthenticatedUsernameNewJobsRoute: AuthenticatedUsernameNewJobsRoute,
  AuthenticatedUsernamePastBookingsRoute:
    AuthenticatedUsernamePastBookingsRoute,
  AuthenticatedUsernameProfileRoute: AuthenticatedUsernameProfileRoute,
  AuthenticatedUsernameSecurityRoute: AuthenticatedUsernameSecurityRoute,
  AuthenticatedUsernameWalletRoute: AuthenticatedUsernameWalletRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface ServicesServiceIdRouteChildren {
  ServicesServiceIdSubServiceIdRoute: typeof ServicesServiceIdSubServiceIdRoute
  ServicesServiceIdIndexRoute: typeof ServicesServiceIdIndexRoute
}

const ServicesServiceIdRouteChildren: ServicesServiceIdRouteChildren = {
  ServicesServiceIdSubServiceIdRoute: ServicesServiceIdSubServiceIdRoute,
  ServicesServiceIdIndexRoute: ServicesServiceIdIndexRoute,
}

const ServicesServiceIdRouteWithChildren =
  ServicesServiceIdRoute._addFileChildren(ServicesServiceIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  UsernameBookRoute: UsernameBookRoute,
  AdminLoginRoute: AdminLoginRoute,
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardHomeownerRoute: DashboardHomeownerRoute,
  DashboardProviderRoute: DashboardProviderRoute,
  NewsIdRoute: NewsIdRoute,
  ServicesServiceIdRoute: ServicesServiceIdRouteWithChildren,
  NewsIndexRoute: NewsIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
